language: python
python: "3.7"
dist: xenial

stages:
  - check
  - lint
  - name: release
    if: tag IS present

cache:
  directories:
    - .venv

before_install:
  - bin/check_version
  - export POETRY_VERSION="1.1.4"
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env

install:
  - poetry config virtualenvs.in-project true
  - poetry install -v

jobs:
  include:
    - stage: check
      name: "Version checking"
      script:
        - bin/check_version
      install: skip
    - stage: lint
      name: "Black linting"
      script:
        - make lint_black
    - stage: lint
      name: "Prettier linting"
      language: node_js
      node_js:
        - 12
      script:
        - make lint_prettier
      before_install: skip
      install: skip
    - stage: lint
      name: "Pylint linting"
      script:
        - make lint_pylint
    - stage: release
      name: "Publish to PyPI"
      before_script:
        - bin/check_release "${TRAVIS_TAG}"
      script:
        - poetry publish --build
      install: skip
